version: "3.3"
services:    
  elasticsearch:
    image: elasticsearch:7.9.1
    volumes:
      - ./esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9300:9300"
      - "9200:9200"
  kibana:
    image: kibana:7.9.1
    ports:
      - "5601:5601" 
volumes:
  esdata:
